# Generated by Django 2.1.5 on 2019-01-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.CharField(max_length=200)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('access_token', models.TextField()),
            ],
        ),
    ]
